### ISSUE TITLE
Can I ask some questions?

### ISSUE THREAD

**Issue by renchihiro** [lifengfan13/P4-INT#2]
Packets can be sent and received between endpoints, why can't traffic be detected on the S3 switch？

**Comment by laofan13** [comment]
Sorry, haven't read the news for several days. can you describe your problem in detail?

**Comment by renchihiro** [comment]
The receiving end can receive the packet, but influxdb does not collect INT information? I'm running receive_report.py on S3, send.py on h1.

**Comment by laofan13** [comment]
you can see P4-INT/report_collector/collector_influxdb.py

**Comment by renchihiro** [comment]
Is it necessary for this report_collector/collector_graphite.py to run?

**Comment by laofan13** [comment]
it is unnecessary

**Comment by laofan13** [comment]
it is unnecessary

**Comment by renchihiro** [comment]
Ok ,thank you very much! ！！I'll try it first.  If there are problems in the future, it may also bother you.....

**Comment by laofan13** [comment]
you also can see https://github.com/GEANT-DataPlaneProgramming/int-platforms

**Comment by renchihiro** [comment]
Okay I got it

**Comment by zxc308** [comment]
^C(p4dev-python-venv) caicai@p4-study:~/INT/P4-INT$ sudo /home/caicai/p4dev-python-venv/bin/python3 receive_report.py   --iface sw-cpu --port 1234
sniffing on s3-cpu-eth1


********* Receiving Telemtry Report ********
###[ INT Report Header v2.0 ]### 
  version   = 1
  hw_id     = 0
  seq_number= 2359296
  node_id   = 536873735
###[ INT Report Individual Header v2.0 ]### 
     rep_type  = 15
     in_type   = 15
     rep_len   = 0
     md_len    = 0
     flag      = 0
     rsvd      = 0
     RepMdBits = 0
     DomainID  = 0
     DSMdBits  = 0
     DSMdstatus= 3
###[ Raw ]### 
        load      = "\x00\x02\x00\x01\x00\x00\x0c\x03\x00\x00\x00\x00\x00\x00\x00\x00\\xce\\xffi\\xbc\x00\x00\x00\x00\\xce\\xffu\\xbf\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x00\x02\x00\x00\x066\x00\x00\x00\x00\x00\x00\x00\x00\\xcf\x00\\xa6\\xa2\x00\x00\x00\x00\\xcf\x00\\xac\\xd8\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x02\x00\x00\x04\\xdd\x00\x00\x00\x00\x00\x00\x00\x00\\xcf\x02#\x00\x00\x00\x00\x00\\xcf\x02'\\xdd\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00hello womrld"

###[ INT Shim header v2.1 ]### 
  type      = 0
  next_protocol= 0
  rsvd      = 0
  int_length= 2
  npt_dependent_field= 1
###[ Raw ]### 
     load      = "\x00\x00\x0c\x03\x00\x00\x00\x00\x00\x00\x00\x00\\xce\\xffi\\xbc\x00\x00\x00\x00\\xce\\xffu\\xbf\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x00\x02\x00\x00\x066\x00\x00\x00\x00\x00\x00\x00\x00\\xcf\x00\\xa6\\xa2\x00\x00\x00\x00\\xcf\x00\\xac\\xd8\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x02\x00\x00\x04\\xdd\x00\x00\x00\x00\x00\x00\x00\x00\\xcf\x02#\x00\x00\x00\x00\x00\\xcf\x02'\\xdd\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00hello womrld"

Traceback (most recent call last):
  File "/home/caicai/INT/P4-INT/receive_report.py", line 151, in <module>
    main()
  File "/home/caicai/INT/P4-INT/receive_report.py", line 147, in main
    sniff(iface = iface,filter='inbound and tcp or udp',
  File "/home/caicai/p4dev-python-venv/lib/python3.10/site-packages/scapy/sendrecv.py", line 1311, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/caicai/p4dev-python-venv/lib/python3.10/site-packages/scapy/sendrecv.py", line 1254, in _run
    session.on_packet_received(p)
  File "/home/caicai/p4dev-python-venv/lib/python3.10/site-packages/scapy/sessions.py", line 109, in on_packet_received
    result = self.prn(pkt)
  File "/home/caicai/INT/P4-INT/receive_report.py", line 148, in <lambda>
    prn = lambda x: handle_pkt(x))
  File "/home/caicai/INT/P4-INT/receive_report.py", line 141, in handle_pkt
    parse_metadata(INTShim(pkt.load))
  File "/home/caicai/INT/P4-INT/receive_report.py", line 121, in parse_metadata
    instructions = (int_pkt[INTMD].instruction_mask_0003 << 4) + int_pkt[INTMD].instruction_mask_0407
  File "/home/caicai/p4dev-python-venv/lib/python3.10/site-packages/scapy/packet.py", line 1327, in __getitem__
    raise IndexError("Layer [%s] not found" % name)
IndexError: Layer [INTMD] not found
请问为什么会这样
